name: chatbot
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  dash_chat_2: ^0.0.21
  path_provider: ^2.1.5
  json_annotation: ^4.9.0
  provider: ^6.1.2
  http: ^1.2.2
  flutter_markdown: ^0.7.4+3
  image_picker: ^1.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
