local:
  weather: {}
  document_generator: {}
#  interpreter: {}
#  artifact: {}
#  openapi_action.OpenAPIActionToolSpec:
#    openapi_uri: The URL or file path of the OpenAPI schema
#  img_gen: {}
  form_filling: {}
llamahub:
  google.GoogleSearchToolSpec:
    engine: <search engine ID>
    key: <google api key>
    num: 2
  wikipedia.WikipediaToolSpec: {}
