local:
  weather: {}
  document_generator: {}
#  interpreter: {}
#  artifact: {}
#  openapi_action.OpenAPIActionToolSpec:
#    openapi_uri: The URL or file path of the OpenAPI schema
#  img_gen: {}
  form_filling: {}
llamahub:
  google.GoogleSearchToolSpec:
    engine: b16258b928ebc4139
    key: AIzaSyB2m8zgJjrYq5ShlkiPseyFpU4gjX2Sgcg
    num: 2
  wikipedia.WikipediaToolSpec: {}
